### ISSUE TITLE
Cluster Features Do Not Inherit Features

### ISSUE THREAD

**Issue by wlerner** [Viglino/OL3-AnimatedCluster#1]
I have a map with a number of features that can appear stacked based on extent and location. The features are stored in a vector layer.  When I select a cluster of features on the map, the cluster animates so I am able to see how many stacked features are present.

However, when I select one of the now unstacked features, I do not see the feature information.

**Comment by Viglino** [comment]
Hello,
The selected feature is itself a cluster feature. That mean the original feature is in the 'features' attribute (whichis an array with just one feature in this case).
Look at the example to see how to retreave the feature with the SelectCluster interaction: line 174 in [index.html](https://github.com/Viglino/OL3-AnimatedCluster/blob/gh-pages/index.html). e.element.get('features') gets the features array and e.element.get('features')[0] is the original feature.

**Comment by wlerner** [comment]
Thank you for getting back to me so quickly.  I am still having an issue which I do not believe is code related.  Maybe the functionality I am looking for is not present.

I populate an array with a number of features through a JSON file which contains information such as name, latitude, longitude, altitude, etc.  Once this array is populated, I had been placing points on the map at the corresponding latitude and longitude and using the built in clustering features of OL3 to let the user know how many features were available.  As the extent changed and the clusters were reduced, I could select the corresponding icon and receive the correct information.

The difficulty I was hoping your code would solve was that sometimes I had multiple features stacked almost directly on top of one another.  I was hoping that I could single click the cluster, have the cluster animate out into a spiral, then select one of the spiraled out elements and that it would contain information from one of the stacked features.

Instead what happens when I select one of the spiraled out elements, all of the features are undefined.  Do the spiraled out clusters inherit the feature information?  I cannot replicate this behavior.  Any assistance is greatly appreciated.

**Comment by Viglino** [comment]
I think there is a bug when using the master branch of OL3. What version are you using? For me the v3.9.1 work well an the SelectCluster interaction retrieves the features in the cluster when click on a spiral.
I'll investigate if the bug comes from the master branch or from the SelectCluster interaction.

**Comment by wlerner** [comment]
I am using 3.11.1.

**Comment by Viglino** [comment]
Hi, I've changed the way I manage the layer of the spiral in the map.
It seems the features on a spiral are now selectable with v3.11.1 using the SelectCluster interaction.

**Comment by wlerner** [comment]
Below are the features I am adding in my program:

```
 var clusterFeature = new ol.Feature({
              geometry: pointGeometry,
              trname: this.name,
              location: this.location,
              latitude: this.latitude,
              longitude: this.longitude,
              altitude: this.altitude,
              lastChecked: this.commsStateTime
            });
```

These are parsed from a large JSON file.  

I then populate an array named `clusterFeature`:

```
clusterFeatures.push(clusterFeature);
```

I add in the selectCluster example, slightly modified for spacing and styling:

```
        var selectCluster = new ol.interaction.SelectCluster({
          pointRadius: 10,
          animate: true,
          featureStyle: animatedClusterStyle
          });

        map.addInteraction(selectCluster);
```

The map is drawn and I see the clusters in their proper locations.  When I click on the cluster, the features spiral out.  So far so good.  However, when I select the cluster, I receive a popup where all is undefined.  Do you think you could code up an example which does more then provide the feature length?  An example which displays latitude and longitude of each feature might go a long way.

**Comment by Viglino** [comment]
I add an 'id' attribute on the features in the example http://viglino.github.io/OL3-AnimatedCluster/.
You can look at the result, you have to listen to adds on the features list of the selectcluster interaction:

``` javascript
selectCluster.getFeatures().on(['add'], function (e)
{   var c = e.element.get('features');
    if (c.length==1)
    {   // First feature in the cluster
        var feature = c[0];
        // Do some stuff with the feature
        var id = feature.get('id');
    }
})
```

**Comment by wlerner** [comment]
After you adjusted your example, I was able to solve my issue.  The updated example shed a lot of light on what I was _not_ doing.  Thank you!
