### ISSUE TITLE
Using an Icon for the feature style causes an error within Firefox

### ISSUE THREAD

**Issue by itsactuallysam** [Viglino/OL3-AnimatedCluster#10]
Using OL 3.20.0 and Firefox 50 if you use the following style for a featureStyle in your SelectCluster the cluster will not render on click and NS_ERROR_NOT_AVAILABLE appears in the console

`featureStyle = new ol.style.Style({`
`    image: new ol.style.Icon(({`
`    new ol.style.Icon(({`
`        anchor: [0.5, 0.5],`
`        anchorXUnits: 'fraction',`
`        anchorYUnits: 'fraction',`
`        opacity: 1,`
`        src: 'image.png',`
`        size: [22, 22]`
`}))`
`});`

It can be worked around by doing the following 

`imageObj = new Image();`
`imageObj.src = 'image.png'`
`featureStyle = new ol.style.Style({`
`    image: new ol.style.Icon(({`
`    new ol.style.Icon(({`
`        img: imageObj,`
`        imgSize: [22, 22]`
`}))`
`});`

**Comment by Viglino** [comment]
Hello,
This is not a cluster issue but a cross domain error when creating the image using ol.style.Icon.
Your hack is the right way to do that.
