### ISSUE TITLE
Selecting(clicking on) the spread feature shows the original cluster parent feature

### ISSUE THREAD

**Issue by 10lojzo** [Viglino/OL3-AnimatedCluster#16]
If you do not specify the same style function in SelectCluster and AnimatedCluster options, you can see, that after singleclick on one of the spread features, the original cluster feature shows up with the style specified in AnimatedCluster. To simulate the behaviour just remove the "style" function from options parameter in ol.interaction.SelectCluster constructor, click on cluster to spread the child features and then click on one of them.

**Comment by Viglino** [comment]
The SelectCluster interaction needs to know how to draw the selected feature. By default the default edit style is used (as it is for the ol.interaction.Select). Clicking on a feature will deselect the other features (or used shift+click for multi selection). This is a normal behaviour.
NB: the style could defined a different style to show the selected feature.

**Comment by 10lojzo** [comment]
I looked in ol documentation for ol.interaction.Select, but could not find any function to set the selected features programatically. I want to achieve the style of the main cluster feature be as selected, when I click on(select) the child spread feature. To be more specific, I want to return undefined for cluster if it is selected(spreaded) and I want it to stay like that even if I click on(select) some of the spread features. But now clicking on spread feature deselects the parent cluster feature which causes the style change back to normal as deselected. I might play with setting some additional cluster feature sign to know it is spreaded, but it is a little bit cumbersome. Thanks for your reply anyway.

**Comment by Viglino** [comment]
To select feature programmatically, just add it to the feature collection of the interaction :
```
selectInteraction.getFeatures().push ( myFeature );
```
but it may conflict with the behaviour of the selectCluster interaction that spread out the cluster when selected.
