### ISSUE TITLE
Spread feature geometry

### ISSUE THREAD

**Issue by 10lojzo** [Viglino/OL3-AnimatedCluster#17]
The spread feature geometry is the same as the original feature geometry. I cannot access new computed "spiral" generated coordinates through spreadFeature.getGeometry().getCoordinates(). It always returns the original coordinates of the hidden feature.

**Comment by Viglino** [comment]
Hello,
The selected features in the select interaction are clusters and you can access there geometry as well.
In the example :
```
selectCluster.getFeatures().on(['add'], function (e)
{     // the cluster geometry
      e.element.getGeometry().getCoordinates();
      // the features in the cluster
      var c = e.element.get('features');
      // Geometry of the first one
      c[0].getGeometry().getCoordinates();
}
```
@+

**Comment by 10lojzo** [comment]
I'm sorry, I have got it. In map.forEachFeatureAtPixel function I reassigned the feature variable with first feature in the cluster and thus I lost the original coordinates. My fault. Thanks.
