### ISSUE TITLE
Animated Cluster - Unable to get property of '0' of undefined or null reference 

### ISSUE THREAD

**Issue by wlerner** [Viglino/OL3-AnimatedCluster#2]
If the extent is changed too quickly (i.e., a user zooms in and out rapidly) when there are clusters displayed on the map, an error can sometimes be generated.  There does not appear to be any code to check if the features length is undefined.

```
Unable to get property '0' of undefined or null reference
```

The error occurs at line 57 in animatedclusterlayer.js section below:

```
/** @private Get the cluster that contains a feature
*/
ol.layer.AnimatedCluster.prototype.getClusterForFeature = function(f, cluster)
{   for (var j=0, c; c=cluster[j]; j++)
    {   var features = cluster[j].get('features');
        //if (features.length > 1) 
        for (var k=0, f2; f2=features[k]; k++)   <== Error Here
        {   if (f===f2) 
            {   return cluster[j];
            }
        }
    }
    return false;
}
```

![error pic 4](https://cloud.githubusercontent.com/assets/14095650/11538533/674ce7b2-98f0-11e5-8e63-948dd24398b7.PNG)

This error can be reproduced under Google Chrome and Internet Explorer.

**Comment by Viglino** [comment]
Right! I've added a test to verify the integrity of the cluster.
Thanks for reporting this bug.

**Comment by wlerner** [comment]
The length verification fix above works wonderfully.  There is another section of code where this error is now occurring.  

```
Unable to get property '0' of undefined or null reference
```

The error occurs at line 101 in animatedclusterlayer.js section below:

```
        for (var i=0, c0; c0=a.cA[i]; i++)
        {   var f = c0.get('features')[0];     <== Error Here
            var c = this.getClusterForFeature (f, a.cB);
            if (c) a.clusters.push({ f:c0, pt:c.getGeometry().getCoordinates() });
        }
```

![error pic 7](https://cloud.githubusercontent.com/assets/14095650/11566531/dc2c9bde-99b0-11e5-8731-39bf5c7cea4e.PNG)

This error can be reproduced under Google Chrome, Firefox 42, and Internet Explorer 11.
Thanks for looking into this issue.

**Comment by Viglino** [comment]
Yep! I now test if the feature is a consistent cluster.
Thanks for taking care of my bugs!

**Comment by wlerner** [comment]
You are welcome!  I appreciate all of your hard work.  Thank you for sharing your code and expertise with the OL3 community.  The last commit solved the problem quite nicely.  I will close the issue.
