### ISSUE TITLE
Why is this repository not integrated in ol-ext?

### ISSUE THREAD

**Issue by CptLausebaer** [Viglino/OL3-AnimatedCluster#21]
I found this project and your other repository [ol-ext](https://github.com/Viglino/ol-ext). 

First of all: Thank you for your awesome work. 👍

My Question is: Why is this repository not integrated in ol-ext? 
It would be nice to have it in one place or at least that this repository is available on npm.

**Comment by Viglino** [comment]
I think it should be!
It was 2 separate project at start but ol-ext grew up and is now available on npm. Thus it would be attractive to merge with it.
We're working on [going to packages to be used in a webpack](https://github.com/Viglino/ol-ext/issues/33#issuecomment-361944616). I'll try to include it on the next release.
