### ISSUE TITLE
Feature Request - Cluster Features Spring Apart Without Selection

### ISSUE THREAD

**Issue by wlerner** [Viglino/OL3-AnimatedCluster#3]
Is it possible to have the clusters spring apart without having to select individual cluster nodes?  For example, when the map has completed loading and the clusters are drawn on the map, can all the clusters > 1 then spring apart without user interaction?

**Comment by Viglino** [comment]
You can use the selectCluster function of the select interaction to make a cluster spring apart (but just one). The function looks for an object with a selected array.

``` javascript
// Get the 12th feature in the cluster layer source
var f = clusterLayer.getSource().getFeatures()[12];
// spring the 12th cluster appart
selectCluster.selectCluster({ selected:[f] })
```

**Comment by wlerner** [comment]
Thank you.  This works for just one as you stated.
