### ISSUE TITLE
Incorrect Option for Animation in selectclusterinteraction.js Class Description

### ISSUE THREAD

**Issue by wlerner** [Viglino/OL3-AnimatedCluster#4]
The `selectclusterinteraction.js` file has an option listed that is incorrect.

`'animation' {bool} option means the cluster will animate when features spread out, default is false`

There does not appear to be an option for animation.  I believe this should be listed as follows:

`'animate' {bool} option means the cluster will animate when features spread out, default is false`

**Comment by Viglino** [comment]
You're right! I change it in the last commit

**Comment by wlerner** [comment]
Thanks!  Sorry for pointing out something so minor.
