### ISSUE TITLE
TypeError when using animatedclusterlayer.js with OL3 Version 3.16.0

### ISSUE THREAD

**Issue by wlerner** [Viglino/OL3-AnimatedCluster#6]
When using with OL3 version 3.16.0, the error below is produced by `animatedclusterlayer.js` at line 156.

``` javascript
vectorContext.setImageStyle is not a function
```

This is because version 3.16.0 no longer supports using this function in this way.  Instead, the code should be updated to call setStyle instead as shown below.

``` javascript
vectorContext.setStyle(imgs);
```

**Comment by Viglino** [comment]
Hello,
Are you sure you're on the last version?
The setImageStyle function has been deprecated in the v.3.14 and `animatedclusterlayer.js` already includes a test to use `setStyle` instead...
Thanks for the feedback anyway ;-)

**Comment by wlerner** [comment]
I did not realize you had upgraded and fixed that function.  I apologize for the non-issue.  Thanks as always for the great work.
