### ISSUE TITLE
animated cluster with no initial source.  

### ISSUE THREAD

**Issue by Shane98c** [Viglino/OL3-AnimatedCluster#7]
Is there a way to create an AnimatedCluster instance that contains no source features initially (they are loaded in/changed later on).  In our initial tests animations are not working when we do this.  

/_create a layer with no source defined_/
var layer = new ol.layer.AnimatedCluster({
           name: 'Cluster',
           animationDuration: 500
});

layer.setSource(clustersource)

Thanks for such a wonderful addition to OL3!

**Comment by Shane98c** [comment]
Solved this by changing this.getSource().on('change'......
 to this.on('change'.....

in animatedclusterlayer.js

Thanks!

**Comment by Viglino** [comment]
You're right I miss this case!
Thanks!
