### ISSUE TITLE
Under what license do you share this code?

### ISSUE THREAD

**Issue by joaorodr84** [Viglino/OL3-AnimatedCluster#9]
Hi,

I know this is not an issue, but I need to ask you.

Under what license do you share this code?

Is it Open Source?

Thanks.

**Comment by joaorodr84** [comment]
Sorry. I didn't see the license inside the code.

**Comment by Viglino** [comment]
All codes are released under the French Opensource BSD compatible CeCILL-B FREE SOFTWARE LICENSE.  

> Full text license in English: (http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.txt)  
> Full text license in French: (http://www.cecill.info/licences/Licence_CeCILL-B_V1-fr.txt)

**Comment by joaorodr84** [comment]
Thanks :)
